# Generated by Django 4.2.5 on 2023-10-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0002_alter_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadContentsFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_import.upload')),
            ],
        ),
        migrations.CreateModel(
            name='UploadContentsFieldValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_import.uploadcontentsfields')),
            ],
        ),
    ]
