# Generated by Django 4.2.5 on 2023-10-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_import', '0003_uploadcontentsfields_uploadcontentsfieldvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
